#!/bin/bash

echo -e "\x1B[94m▶ Git Hooks (pre commit)\x1B[0m"

folder="/home/dragonis41/.git-hooks/pre-commit.d"

# Check if the directory exist.
if [[ ! -d $folder ]]; then
  echo "Error: the folder $folder doesn't exist"
  exit 1
fi

for file in "$folder"/*; do
  # Check if the file is executable.
  if [ -x "$file" ]; then
    # Execute the file.
    if ! "$file"; then
      exit 1
    fi
  fi
done
echo "" # Empty line.
