#!/bin/bash

echo -e "\x1B[94m▶ Git Hooks (prepare commit msg)\x1B[0m"

folder="/home/dragonis41/.git-hooks/prepare-commit-msg.d"

# Check if the directory exists
if [[ ! -d $folder ]]; then
  echo "Error: the folder $folder doesn't exist"
  exit 1
fi

for file in "$folder"/*; do
  # Check if the file is executable
  if [ -x "$file" ]; then
    # Execute the file with all original arguments
    if ! "$file" "$1" "$2" "$3"; then
      exit 1
    fi
  fi
done
echo ""
